nodeSelector:
  production: worker

config:
  BinderHub:
    base_url: /binder/
    hub_url: https://notebooks.gesis.org/binder/jupyter/

    use_registry: true
    image_prefix: gesiscss/orc-binder-
    build_image: jupyter/repo2docker:9f081a2
    per_repo_quota: 100
    build_node_selector:
      user: workers
    appendix: |
      USER root
      ENV BINDER_URL={binder_url}
      ENV REPO_URL={repo_url}
      RUN cd /tmp \
       && wget -q https://github.com/gesiscss/orc/archive/master.tar.gz -O orc.tar.gz \
       && tar --wildcards -xzf orc.tar.gz --strip 2 */binderhub/appendix\
       && ./appendix/run-appendix \
       && rm -rf orc.tar.gz appendix
      USER $NB_USER

    template_variables:
      is_staging: False
      is_production: True
    template_path: /etc/binderhub/templates/binderhub/templates
    #extra_static_path: /etc/binderhub/templates/binderhub/static
    #extra_static_url_prefix: extra_static/

  GitHubRepoProvider:
    # Add banned repositories to the list below
    # They should be strings that will match "^<org-name>/<repo-name>.*"
    banned_specs:
      # e.g. '^org/repo.*'
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*

resources:
  requests:
    cpu: "0.25"
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi

service:
  annotations:
    prometheus.io/path: '/binder/metrics'
  type: NodePort
  nodePort: 30081

dind:
  enabled: true

imageCleaner:
  enabled: false

initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=master
      - --depth=1
      - --
      - https://github.com/gesiscss/orc.git
      - /etc/binderhub/templates
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/templates
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/templates

cors: &cors
  allowOrigin: "*"

jupyterhub:
  custom:
    cors: *cors
  hub:
    baseUrl: /binder/jupyter/
    nodeSelector:
      production: worker
    annotations:
      prometheus.io/path: "/binder/jupyter/hub/metrics"
    deploymentStrategy:
      type: RollingUpdate
    db:
      type: postgres
    resources:
      requests:
        cpu: "0.25"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
    extraConfig:
      neverRestart: |
        c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})

  proxy:
    nodeSelector:
      production: worker
    https:
      enabled: false
    service:
      type: NodePort
      nodePorts:
        http: 30082
    chp:
      resources:
        requests:
          cpu: "0.25"
          memory: 512Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  singleuser:
    cpu:
      guarantee: 0.2
      limit: 2
    memory:
      guarantee: 2G
      limit: 8G
    extraEnv:
      # settings for kernel culling
      # to be used in binderhub/appendix/extra_notebook_config.py
      CULL_CONNECTED: '1'
      CULL_TIMEOUT: '900'
      CULL_KERNEL_TIMEOUT: '900'
      CULL_INTERVAL: '60'
    nodeSelector:
      user: workers

  cull:
    # cull every 16 minutes so it is out of phase
    # with the proxy check-routes interval of five minutes
    timeout: 900
    every: 960
    # maxAge is 6 hours: 6 * 3600 = 21600
    maxAge: 21600

