apiVersion: v1
kind: Service
metadata:
  name: orc-site-test
  labels:
    app: orc-site-test
spec:
  type: NodePort
  selector:
    app: orc-site-test
  ports:
  - name: "http"
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30178
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc-site-test
  labels:
    app: orc-site-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orc-site-test
  template:
    metadata:
      name: orc-site-test
      labels:
        app: orc-site-test
    spec:
      containers:
      - name: orc-site-test
        image: gesiscss/orc-site:e4ee02c
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:5000", "-w", "4", "orc_site.app:app"]
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: FLASK_ENV
          value:  "production"
        resources:
          requests:
            cpu: "0.25"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
