elasticsearch:
  # https://github.com/elastic/helm-charts/tree/7.9.3/elasticsearch
  enabled: true
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "8Gi"
  replicas: 2
  volumeClaimTemplate:
    resources:
      requests:
        storage: 90Gi

logstash:
  # https://github.com/elastic/helm-charts/blob/7.9.3/logstash
  enabled: false
  image: "docker.elastic.co/logstash/logstash-oss"
  resources:
    requests:
      cpu: "100m"
      memory: "1536Mi"
    limits:
      cpu: "2000m"
      memory: "3172Mi"
  replicas: 2

  volumeClaimTemplate:
    resources:
      requests:
        storage: 30Gi

  # connect to elasticsearch
  # https://github.com/elastic/helm-charts/tree/7.9.3/logstash/examples/elasticsearch
  persistence:
    enabled: true
  logstashConfig:
    logstash.yml: |
      http.host: 0.0.0.0
    # xpack.monitoring.enabled: false
  logstashPipeline:
    uptime.conf: |
      input { exec { command => "uptime" interval => 30 } }
      output { elasticsearch { hosts => ["http://elasticsearch-master:9200"] index => "logstash" } }
#
#  # we have to mount this for user:worker,
#  # there we have docker data dir not in default path (/var/lib/docker) but under /ssd/docker
#  extraVolumes: |-
#   - name: customvarlibdockercontainers
#     hostPath:
#       path: /ssd/docker/containers
#  extraVolumeMounts: |-
#   - name: customvarlibdockercontainers
#     mountPath: /ssd/docker/containers
#     readOnly: true

kibana:
  # https://github.com/elastic/helm-charts/tree/7.9.3/kibana
  enabled: true
  image: "docker.elastic.co/kibana/kibana-oss"
  #elasticsearchHosts: "http://oss-master:9200"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  nodeSelector:
    base: worker

filebeat:
  # https://github.com/elastic/helm-charts/tree/7.9.3/filebeat
  image: docker.elastic.co/beats/filebeat-oss
  # https://github.com/elastic/helm-charts/tree/7.9.3/filebeat#why-is-filebeat-hostname-field-set-to-kubernetes-pod-name
  hostNetworking: false

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "2000m"
      memory: "400Mi"

  #hostPathRoot: /var/lib
  # we have to mount this for user:worker,
  # there we have docker data dir not in default path (/var/lib/docker) but under /ssd/docker
  extraVolumes:
   - name: customvarlibdockercontainers
     hostPath:
       path: /ssd/docker/containers
  extraVolumeMounts:
   - name: customvarlibdockercontainers
     mountPath: /ssd/docker/containers
     readOnly: true