apiVersion: v1
kind: Service
metadata:
  name: gallery
  labels:
    app: gallery
spec:
  type: NodePort
  selector:
    app: gallery
  ports:
  - name: "http"
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      name: gallery
      labels:
        app: gallery
    spec:
      nodeSelector:
        base: worker  # where database is
      containers:
      - name: gallery
        image: gesiscss/binder-gallery:79d7eab
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:5000", "-w", "16", "binder_gallery:app"]
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: FLASK_ENV
          value:  "production"
        - name: BG_BASE_URL
          value:  "/gallery/"
        - name: BG_APPLICATION_SETTINGS
          value:  "gallery_config.Config"
        - name: PRODUCTION_SERVER
          value: "true"
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "4"
            memory: "4Gi"
        volumeMounts:
        - name: gallery-config
          mountPath: /binder_gallery/gallery_config.py
          subPath: _secret_config.py
          readOnly: true
      volumes:
      - name: gallery-config
        secret:
          secretName: gallery-config
