apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mybinder-archive-parser
spec:
  # run every day every hour (in UTC)
  schedule: "0 * * * *"
  # Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 70
  jobTemplate:
    spec:
      template:
        metadata:
          name: mybinder-archive-parser
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            base: worker  # where database is
          containers:
          - name: mybinder-archive-parser
            image: gesiscss/binder-gallery:d002b6f
            command: ["flask"]
            args: ["parse-mybinder-archives", "--with-description", "mybinder"]
            ports:
            - containerPort: 5000
              protocol: TCP
            env:
            - name: FLASK_APP
              value:  "binder_gallery"
            - name: FLASK_ENV
              value:  "production"
            - name: BG_BASE_URL
              value:  "/gallery/"
            - name: BG_APPLICATION_SETTINGS
              value:  "gallery_config.Config"
            - name: PRODUCTION_SERVER
              value: "true"
            volumeMounts:
            - name: gallery-config
              mountPath: /binder_gallery/gallery_config.py
              subPath: _secret_config.py
              readOnly: true
          volumes:
          - name: gallery-config
            secret:
              secretName: gallery-config
