apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mybinder-archive-parser
spec:
  # run every day from 1 am to 10 pm (in UTC) each 3 hours
  schedule: "0 1,4,7,10,13,16,19,22 * * *"
  # Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 70
  jobTemplate:
    spec:
      template:
        metadata:
          name: mybinder-archive-parser
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            base: worker  # where database is
          containers:
          - name: mybinder-archive-parser
            image: gesiscss/binder-gallery:88655c0
            command: ["flask"]
            args: ["parse-mybinder-archives", "mybinder"]
            ports:
            - containerPort: 5000
              protocol: TCP
            env:
            - name: FLASK_APP
              value:  "binder_gallery"
            - name: FLASK_ENV
              value:  "production"
            - name: BG_BASE_URL
              value:  "/gallery/"
            - name: BG_APPLICATION_SETTINGS
              value:  "gallery_config.Config"
            #- name: PRODUCTION_SERVER
            #  value: "true"
            volumeMounts:
            - name: gallery-config
              mountPath: /binder_gallery/gallery_config.py
              subPath: _secret_config_test.py
              readOnly: true
          volumes:
          - name: gallery-config
            secret:
              secretName: gallery-config
