projectName: gesis-hub-prod

jupyterhub:
  hub:
    # below is already default of z2jh chart
    #service:
    #  annotations:
    #    prometheus.io/path: "/hub/metrics"
    resources:
      requests:
        cpu: "0.25"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
    extraEnv:
      OAUTH2_AUTHORIZE_URL: https://login.gesis.org/realms/gesis/protocol/openid-connect/auth
      OAUTH2_TOKEN_URL: https://login.gesis.org/realms/gesis/protocol/openid-connect/token
      OAUTH_CALLBACK_URL: https://notebooks.gesis.org/hub/oauth_callback

  # https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#openid-connect
  auth:
    custom:
      config:
        login_service: "GESIS Login"  # to customize the label on the login button
        token_url: https://login.gesis.org/realms/gesis/protocol/openid-connect/token
        userdata_url: https://login.gesis.org/realms/gesis/protocol/openid-connect/userinfo

  proxy:
    service:
      nodePorts:
        http: 30080
    chp:
      resources:
        requests:
          cpu: "0.5"
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi

  singleuser:
    storage:
      # has no effect when using nfs: this is a min limit not a max
      capacity: 25Gi
    cpu:
      guarantee: 0.1
      limit: 1
    memory:
      guarantee: 1G
      limit: 32G
