jupyterhub:
  debug:
    enabled: true

  hub:
    service:
      annotations:
        prometheus.io/scrape: 'false'
    extraConfig:
      010-orc: |
        c.JupyterHub.bind_url = 'https://notebooks-test.gesis.org'
      020-templates: |
        staging = True
        production = False
    resources:
      requests:
        cpu: "0.25"
        memory: 512Mi
      limits:
        cpu: "0.5"
        memory: 1Gi
    extraEnv:
      OAUTH2_AUTHORIZE_URL: https://notebooks-test.gesis.org/auth/realms/gesis/protocol/openid-connect/auth
      OAUTH2_TOKEN_URL: https://notebooks-test.gesis.org/auth/realms/gesis/protocol/openid-connect/token
      OAUTH_CALLBACK_URL: https://notebooks-test.gesis.org/hub/oauth_callback

  auth:
    custom:
      config:
        login_service: "Test Login"
        token_url: https://notebooks-test.gesis.org/auth/realms/gesis/protocol/openid-connect/token
        userdata_url: https://notebooks-test.gesis.org/auth/realms/gesis/protocol/openid-connect/userinfo

  proxy:
    service:
      nodePorts:
        http: 30180
    chp:
      resources:
        requests:
          cpu: "0.1"
          memory: 256Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  singleuser:
    storage:
      # has no effect when using nfs: this is a min limit not a max
      capacity: 5Gi
    cpu:
      guarantee: 0.1
      limit: 0.5
    memory:
      guarantee: 512M
      limit: 512M
