jupyterhub:
  hub:
    # below is already default of z2jh chart
    #service:
    #  annotations:
    #    prometheus.io/path: "/hub/metrics"
    extraConfig:
      010-orc: |
        c.JupyterHub.bind_url = 'https://notebooks.gesis.org'
      020-templates: |
        staging = False
        production = True
    resources:
      requests:
        cpu: "0.25"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi

    # clone custom JupyterHub templates into a volume
    initContainers:
      - name: git-clone-templates
        image: alpine/git
        args:
          - clone
          - --single-branch
          - --branch=master
          - --depth=1
          - --
          - https://github.com/gesiscss/orc.git
          - /etc/jupyterhub/custom
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: custom-templates
            mountPath: /etc/jupyterhub/custom
    extraVolumes:
      - name: custom-templates
        emptyDir: {}
    extraVolumeMounts:
      - name: custom-templates
        mountPath: /etc/jupyterhub/custom

  # https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#openid-connect
  auth:
    custom:
      config:
        login_service: "GESIS Login"  # to customize the label on the login button
        token_url: https://login.gesis.org/realms/gesis/protocol/openid-connect/token
        userdata_url: https://login.gesis.org/realms/gesis/protocol/openid-connect/userinfo

  proxy:
    service:
      nodePorts:
        http: 30080
    chp:
      resources:
        requests:
          cpu: "0.1"
          memory: 256Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  singleuser:
    storage:
      # has no effect when using nfs: this is a min limit not a max
      capacity: 25Gi
    cpu:
      guarantee: 0.1
      limit: 2
    memory:
      guarantee: 1G
      limit: 4G
