jupyterhub:
  hub:
    # below is already default of z2jh chart
    #service:
    #  annotations:
    #    prometheus.io/path: "/hub/metrics"
    extraConfig:
      010-orc: |
        c.JupyterHub.bind_url = 'https://notebooks.gesis.org'
      020-templates: |
        staging = False
        production = True
    resources:
      requests:
        cpu: "0.25"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi

  proxy:
    service:
      nodePorts:
        http: 30080
    chp:
      resources:
        requests:
          cpu: "0.1"
          memory: 256Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  singleuser:
    storage:
      # has no effect when using nfs: this is a min limit not a max
      capacity: 25Gi
    cpu:
      guarantee: 0.1
      limit: 2
    memory:
      guarantee: 1G
      limit: 4G
