# based on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/minikube-config.yaml
# TODO for static files (based on orc site): https://discourse.jupyter.org/t/customizing-jupyterhub-on-kubernetes/1769/6
jupyterhub:
  debug:
    enabled: true
  hub:
    nodeSelector:
      base: null
    extraConfig:
#      010-orc: |
#        # minikube ip -> 192.168.99.100
#        c.JupyterHub.bind_url = 'http://192.168.99.100:31212'
      011-orc: |
        # c.JupyterHub.refresh_pre_spawn = True
        c.JupyterHub.redirect_to_server = False
    resources:
      requests:
        cpu: 0
        memory: 0

  auth:
    type: dummy
    admin:
      users:
        - admin

  proxy:
    service:
      type: NodePort
      nodePorts:
        http: 31212
    chp:
      resources:
        requests:
          memory: 0
          cpu: 0

  singleuser:
    nodeSelector:
      user: null
    storage:
      type: none
    memory:
      guarantee: null

  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
