binderhub:
  resources:
    requests:
      cpu: "0.25"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

  # clone custom binder templates into a volume
  initContainers:
    - name: git-clone-templates
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --branch=master
        - --depth=1
        - --
        - https://github.com/gesiscss/orc.git
        - /etc/binderhub/custom
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: custom-templates
          mountPath: /etc/binderhub/custom
  extraVolumes:
    - name: custom-templates
      emptyDir: {}
  extraVolumeMounts:
    - name: custom-templates
      mountPath: /etc/binderhub/custom

  config:
    BinderHub:
      hub_url: https://notebooks.gesis.org/binder/jupyter/
      image_prefix: gesiscss/orc-binder-
      appendix: |
        USER root
        ENV BINDER_URL={binder_url}
        ENV REPO_URL={repo_url}
        RUN cd /tmp \
         && wget -q https://github.com/gesiscss/orc/archive/master.tar.gz -O orc.tar.gz \
         && tar --wildcards -xzf orc.tar.gz --strip 2 */gesisbinder/appendix\
         && ./appendix/run-appendix \
         && rm -rf orc.tar.gz appendix
        USER $NB_USER

  extraConfig:
    020-templates: |
      staging = False
      production = True

  service:
    annotations:
      prometheus.io/path: '/binder/metrics'
    nodePort: 30081

  jupyterhub:
    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
       # below is already default of z2jh chart
      #service:
      #  annotations:
      #    prometheus.io/scrape: 'true'
      #    prometheus.io/path: '/binder/jupyter/hub/metrics'

    proxy:
      service:
        nodePorts:
          http: 30082
      chp:
        resources:
          requests:
            cpu: "0.1"
            memory: 256Mi
          limits:
            cpu: "0.5"
            memory: 512Mi

    singleuser:
      cpu:
        guarantee: 0.1
        limit: 2
      memory:
        guarantee: 1G
        limit: 8G
