binderhub:
  resources:
    requests:
      cpu: "0.1"
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  config:
    BinderHub:
      debug: true
      hub_url: https://notebooks-test.gesis.org/binder/jupyter/
      image_prefix: gesiscss/orc-binder-staging-

  extraConfig:
    020-templates: |
      staging = True
      production = False

  service:
    annotations:
      prometheus.io/scrape: 'false'
    nodePort: 30181

  jupyterhub:
    debug:
      enabled: true

    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      service:
        annotations:
          prometheus.io/scrape: 'false'

    proxy:
      service:
        nodePorts:
          http: 30182
      chp:
        resources:
          requests:
            cpu: "0.1"
            memory: 256Mi
          limits:
            cpu: "0.5"
            memory: 512Mi

    singleuser:
      cpu:
        guarantee: 0.1
        limit: 0.5
      memory:
        guarantee: 256M
        limit: 512M
