projectName: gesis-binder-staging

binderhub:
  resources:
    requests:
      cpu: "0.1"
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  extraVolumes:
    - name: binder-templates
      configMap:
        name: binder-templates
    - name: binder-templates-gesis
      configMap:
        name: binder-templates-gesis
  extraVolumeMounts:
    - name: binder-templates
      mountPath: /etc/binderhub/templates
    - name: binder-templates-gesis
      mountPath: /etc/binderhub/templates/gesis

  config:
    BinderHub:
      debug: true
      hub_url: https://notebooks-test.gesis.org/binder/jupyter/
      image_prefix: gesiscss/orc-binder-staging-

  service:
    annotations:
      prometheus.io/scrape: 'false'
    nodePort: 30181

  jupyterhub:
    debug:
      enabled: true

    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      service:
        annotations:
          prometheus.io/scrape: 'false'

    proxy:
      service:
        nodePorts:
          http: 30182
      chp:
        resources:
          requests:
            cpu: "0.1"
            memory: 256Mi
          limits:
            cpu: "0.5"
            memory: 512Mi

    singleuser:
      cpu:
        guarantee: 0.1
        limit: 0.5
      memory:
        guarantee: 256M
        limit: 512M

# no need to enable this. prod image_prefix (gesiscss/orc-binder-) covers
# staging image_prefix (gesiscss/orc-binder-staging-)
imageCleaner:
  enabled: false
