apiVersion: v1
kind: Service
metadata:
  name: nginx-shibboleth
  labels:
    app: nginx-shibboleth
spec:
  # type: ClusterIP
  selector:
    app: nginx-shibboleth
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
  - name: https
    protocol: TCP
    targetPort: 443
    port: 443
  # https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
  externalIPs:
    - 194.95.75.9
    #- 194.95.75.12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-shibboleth
  labels:
    app: nginx-shibboleth
spec:
  replicas: 1
  # The selector field defines how the Deployment finds which Pods to manage.
  selector:
    matchLabels:
      app: nginx-shibboleth
  template:
    metadata:
      name: nginx-shibboleth
      labels:
        app: nginx-shibboleth
    spec:
      nodeSelector:
        production: worker
      containers:
      - name: nginx-shibboleth
        image: gesiscss/nginx-shibboleth-orc:c81f03fe
        command: ["/bin/sh"]
        args: ["-c", "cp /etc/shibboleth-conf/* /etc/shibboleth/ && /usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf"]
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: shibboleth-sp-conf
          mountPath: /etc/shibboleth-conf
        - name: shibboleth-sp-tls
          mountPath: "/etc/shibboleth/tls"
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: letsencrypt-volume
          mountPath: "/etc/letsencrypt_volume"
          readOnly: true
        - name: webroot-volume
          mountPath: "/var/www/html"
          readOnly: true
      volumes:
      - name: shibboleth-sp-conf
        configMap:
          name: shibboleth-configmap
      - name: shibboleth-sp-tls
        secret:
          secretName: shibboleth-sp-tls-secret
      - name: nginx-conf
        configMap:
          name: nginx-configmap
      - name: letsencrypt-volume
        hostPath:
          path: /etc/letsencrypt
      - name: webroot-volume
        hostPath:
          path: /var/www/html