apiVersion: v1
kind: Service
metadata:
  name: nginx-shibboleth-test-service
  labels:
    app: nginx-shibboleth-test
spec:
  type: NodePort
  selector:
    app: nginx-shibboleth-test
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 30176
  - name: https
    protocol: TCP
    targetPort: 443
    port: 443
    nodePort: 30177
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-shibboleth-test-deployment
  labels:
    app: nginx-shibboleth-test
spec:
  replicas: 1
  # The selector field defines how the Deployment finds which Pods to manage.
  selector:
    matchLabels:
      app: nginx-shibboleth-test
  strategy:
    # rollingUpdate:
      # maxSurge: 1
      # maxUnavailable: 0
    type: RollingUpdate  # default
  template:
    metadata:
      name: nginx-shibboleth-test-pod
      labels:
        app: nginx-shibboleth-test
      # annotations:
        # TODO when helm is used, we can checksum config and secret files
        # https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change
        # This lets us autorestart when the configmaps/secrets change!
        #checksum/config: {{ include (print "~/ilcm/orc/nginx/k8s_test") . | sha256sum }}
    spec:
      restartPolicy: Always  # default
#      hostNetwork: true
      nodeSelector:
        # assign this pod to staging server
        staging: worker
      containers:
      - name: nginx-shibboleth-test
        image: gesiscss/nginx-shibboleth-orc:c81f03fe
        # https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#run-a-command-in-a-shell
        command: ["/bin/sh"]
        args: ["-c", "cp /etc/shibboleth-conf/* /etc/shibboleth/ && /usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf"]
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: shibboleth-sp-conf
          mountPath: /etc/shibboleth-conf
        - name: shibboleth-sp-tls
          mountPath: "/etc/shibboleth/tls"
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: nginx-htpasswd
          mountPath: "/etc/nginx/.htpasswd"
          readOnly: true
        - name: letsencrypt-manual
          mountPath: "/etc/nginx/letsencrypt-manual"
          readOnly: true
        - name: letsencrypt
          mountPath: "/etc/letsencrypt"
          readOnly: true
        - name: letsencrypt-dhparam
          mountPath: "/etc/letsencrypt_dhparam"
          readOnly: true
      volumes:
      - name: shibboleth-sp-conf
        configMap:
          name: shibboleth-configmap
      - name: shibboleth-sp-tls
        secret:
          secretName: shibboleth-sp-tls-secret
      - name: nginx-conf
        configMap:
          name: nginx-configmap
      - name: nginx-htpasswd
        secret:
          secretName: nginx-htpasswd-secret
      - name: letsencrypt-manual
        secret:
          secretName: letsencrypt-manual-secret
      - name: letsencrypt
        secret:
          secretName: letsencrypt-secret
      - name: letsencrypt-dhparam
        secret:
          secretName: letsencrypt-dhparam-secret
