apiVersion: v1
kind: Service
metadata:
  name: nginx-shibboleth-service
  labels:
    app: nginx-shibboleth
spec:
  type: NodePort
  selector:
    app: nginx-shibboleth
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 30076
  - name: https
    protocol: TCP
    targetPort: 443
    port: 443
    nodePort: 30077
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-shibboleth-deployment
  labels:
    app: nginx-shibboleth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-shibboleth
  strategy:
    type: RollingUpdate  # default
  template:
    metadata:
      name: nginx-shibboleth-pod
      labels:
        app: nginx-shibboleth
    spec:
      restartPolicy: Always  # default
      nodeSelector:
        production: worker
      containers:
      - name: nginx-shibboleth
        image: gesiscss/nginx-shibboleth-orc:c81f03fe
        command: ["/bin/sh"]
        args: ["-c", "cp /etc/shibboleth-conf/* /etc/shibboleth/ && /usr/bin/supervisord --nodaemon --configuration /etc/supervisor/supervisord.conf"]
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: shibboleth-sp-conf
          mountPath: /etc/shibboleth-conf
        - name: shibboleth-sp-tls
          mountPath: "/etc/shibboleth/tls"
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: letsencrypt-manual
          mountPath: "/etc/nginx/letsencrypt-manual"
          readOnly: true
        - name: letsencrypt
          mountPath: "/etc/letsencrypt"
          readOnly: true
        - name: letsencrypt-dhparam
          mountPath: "/etc/letsencrypt_dhparam"
          readOnly: true
      volumes:
      - name: shibboleth-sp-conf
        configMap:
          name: shibboleth-configmap
      - name: shibboleth-sp-tls
        secret:
          secretName: shibboleth-sp-tls-secret
      - name: nginx-conf
        configMap:
          name: nginx-configmap
      - name: letsencrypt-manual
        secret:
          secretName: letsencrypt-manual-secret
      - name: letsencrypt
        secret:
          secretName: letsencrypt-secret
      - name: letsencrypt-dhparam
        secret:
          secretName: letsencrypt-dhparam-secret
