# https://github.com/helm/charts/blob/master/stable/grafana/values.yaml

service:
  type: NodePort
  port: 80
  nodePort: 30075

nodeSelector:
  production: worker

resources:
  requests:
    cpu: "0.2"
    memory: 512Mi
  limits:
    cpu: "0.5"
    memory: 512Mi

persistence:
  enabled: true
  # has no effect when using nfs: this is a min limit not a max
  size: 10Gi
  accessModes:
    - ReadWriteOnce
#  existingClaim:

# https://grafana.com/plugins
# Pass the plugins you want installed as a comma separated list.
# plugins: "digrich-bubblechart-panel,grafana-clock-panel"
# https://grafana.com/plugins/grafana-kubernetes-app
#plugins: "grafana-kubernetes-app"

# http://docs.grafana.org/installation/configuration/
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
  auth.basic:
    enabled: true
  smtp:
    enabled: true
  server:
    root_url: "https://notebooks.gesis.org/grafana/"
    http_port: 3000

# http://docs.grafana.org/administration/provisioning/#datasources
# http://docs.grafana.org/features/datasources/prometheus/
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: prometheus
        orgId: 1
        type: prometheus
        url: http://prometheus-server:9090
        access: proxy  # server
        isDefault: true
        editable: false
