# chart version 4.3.0: https://github.com/helm/charts/tree/12088766a9cbb5fafc61e643df3b8c41814dfae8/stable/grafana

service:
  type: NodePort
  port: 80  # default
  nodePort: 30075

nodeSelector:
  base: worker

resources:
  requests:
    cpu: "0.1"
    memory: 128Mi
  limits:
    cpu: "0.5"
    memory: 512Mi

persistence:
  enabled: true
  # has no effect when using nfs: this is a min limit not a max
  size: 10Gi  # default
  accessModes:
    - ReadWriteOnce  # default

# https://grafana.com/plugins
# Pass the plugins you want installed as a comma separated list.
# plugins: "digrich-bubblechart-panel,grafana-clock-panel"
# https://grafana.com/plugins/grafana-kubernetes-app
#plugins: "grafana-kubernetes-app"

# http://docs.grafana.org/installation/configuration/
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
  auth.basic:
    enabled: true
  smtp:
    enabled: true
  server:
    root_url: "https://notebooks.gesis.org/grafana/"
    http_port: 3000

# http://docs.grafana.org/administration/provisioning/#datasources
# http://docs.grafana.org/features/datasources/prometheus/
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: prometheus
        orgId: 1
        type: prometheus
        url: http://prometheus-server:80
        access: proxy  # server
        isDefault: true
        editable: false
