# chart version version 11.12.1: https://github.com/helm/charts/tree/495ecb8573f2008e02fedf331c01a99f0d41bcca/stable/prometheus
alertmanager:
  # TODO
  enabled: false
pushgateway:
  enabled: false

server:
#  nodeSelector:
#    base: worker
  service:
    type: NodePort
    nodePort: 30073
    # used in grafana_config.yaml: datasources.datasources.yaml.datasources.url
    servicePort: 80  # default
  resources:
    requests:
      cpu: "1"
      memory: 8Gi
    limits:
      cpu: "2"
      memory: 16Gi
  persistentVolume:
    # has no effect when using nfs: this is a min limit not a max
    size: 96Gi
#    existingClaim:
  retention: 60d

#kubeStateMetrics:
#  nodeSelector:
#    base: worker
#  resources:
