# https://github.com/helm/charts/tree/master/stable/prometheus
nodeExporter:
  updateStrategy:
    type: RollingUpdate
alertmanager:
  # TODO
  enabled: false
pushgateway:
  enabled: false

server:
  nodeSelector:
    production: worker
  service:
    type: NodePort
    nodePort: 30073
    servicePort: 9090
  resources:
    requests:
      cpu: "2"
      memory: 12Gi
    limits:
      cpu: "2"
      memory: 12Gi
  persistentVolume:
    # has no effect when using nfs: this is a min limit not a max
    size: 64Gi
#    existingClaim:
  retention: 60d

kubeStateMetrics:
  nodeSelector:
    production: worker
#  resources:
