elasticsearch:
  # https://github.com/helm/charts/tree/master/stable/elasticsearch#configuration
  # https://github.com/helm/charts/blob/master/stable/elasticsearch/values.yaml
  enabled: true
  # https://github.com/helm/charts/tree/master/stable/elasticsearch#enabling-elasticsearch-internal-monitoring
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
  cluster:
    xpackEnable: true
    env:
      XPACK_MONITORING_ENABLED: true
      # https://github.com/helm/charts/tree/master/stable/elasticsearch#minimum-master-nodes
      MINIMUM_MASTER_NODES: "2"  # (number of master-eligible nodes (2) / 2) + 1

  master:
    persistence:
      size: "12Gi"

  data:
    persistence:
      size: "90Gi"


kibana:
  # https://github.com/helm/charts/tree/master/stable/kibana#configuration
  enabled: true
  nodeSelector:
    base: worker  # we need this for filebeat
  # https://github.com/helm/charts/tree/master/stable/elasticsearch#enabling-elasticsearch-internal-monitoring
  image:
    repository: "docker.elastic.co/kibana/kibana"

  service:
    type: NodePort
    nodePort: 30070

  env:
    # All Kibana configuration options are adjustable via env vars.
    # To adjust a config option to an env var uppercase + replace `.` with `_`
    # Ref: https://www.elastic.co/guide/en/kibana/current/settings.html

    # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services
    ELASTICSEARCH_HOSTS: http://efk-stack-elasticsearch-client.efk-stack-ns.svc.cluster.local:9200
    #XPACK_SECURITY_ENABLED: "true"
  files:
    kibana.yml:
      ## Default Kibana configuration from kibana-docker.
      elasticsearch.hosts: http://efk-stack-elasticsearch-client.efk-stack-ns.svc.cluster.local:9200
      ## Custom config properties below
      ## Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
      server.basePath: "/kibana"
      server.rewriteBasePath: true

  #resources: {}

  # https://github.com/helm/charts/tree/master/stable/kibana#dasboard-import
  # A dashboard is defined by a name and a string with the json payload or the download url
#  dashboardImport:
#    enabled: true
#    timeout: 60
##    xpackauth:
##      enabled: false
##      username: myuser
##      password: mypass
#    dashboards:
#      #k8s: https://raw.githubusercontent.com/monotek/kibana-dashboards/master/k8s-fluentd-elasticsearch.json  # error: Saved objects file format is invalid and cannot be imported.
#      k8s2: https://raw.githubusercontent.com/carlosedp/kubernetes-elasticsearch-cluster/master/Kibana-dashboards.json

logstash:
  enabled: false

fluentd-elasticsearch:
  # https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch#configuration
  enabled: true
  elasticsearch:
    host: 'efk-stack-elasticsearch-client'  # elasticsearch client service name
    # better use default prefix "logstash"
    # Kibana-dashboards.json also uses it
    #logstash_prefix: 'orc-logstash'
  # we have to mount this for main worker, there we have docker data dir not in default path (/var/lib/docker) but under /ssd/docker
  extraVolumes:
    - name: customvarlibdockercontainers
      hostPath:
        path: /ssd/docker/containers
  extraVolumeMounts:
    - name: customvarlibdockercontainers
      mountPath: /ssd/docker/containers
      readOnly: true

#  secret:
#  # - name: ELASTICSEARCH_PASSWORD
#  #   secret_name: elasticsearch
#  #   secret_key: password