#image:
#  # https://quay.io/repository/kubernetes_incubator/nfs-provisioner?tag=latest&tab=tags
#  repository: quay.io/kubernetes_incubator/nfs-provisioner
#  tag: v2.2.1-k8s1.12

persistence:
  enabled: true
  storageClass: "-"
  size: 4000Gi

storageClass:
  defaultClass: true
  # Allow base storage PCV to be dynamically resizeable (set to null to disable )
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims
#  allowVolumeExpansion: null

nodeSelector:
  # because we use hostPath (see pv.yaml)
  base: worker
