apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-nfs-server-provisioner-0
spec:
  capacity:
    storage: 4000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /xfs/nfs
  claimRef:
    namespace: default
    name: data-nfs-nfs-server-provisioner-0