kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
     storageclass.beta.kubernetes.io/is-default-class: "true"
  name: nfs-sc
provisioner: orc.external/nfs
reclaimPolicy: Delete