kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-scripts
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]  # delete is for delete-pods script
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-scripts
subjects:
- kind: ServiceAccount
  namespace: default
  name: pod-scripts
roleRef:
  kind: ClusterRole
  name: pod-scripts
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-scripts
