# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
hub:
  baseUrl: /jupyter/
#  nodeSelector:
#    worker1: production
  image:
    name: gesiscss/k8s-hub-orc
    tag: "c5b94aa2"
  db:
    type: postgres
  extraConfig: |
    c.Authenticator.shibboleth_logout_url = 'https://notebooks.gesis.org/Shibboleth.sso/Logout?return=https://notebooks.gesis.org/'
  resources:
    requests:
      cpu: "0.5"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

proxy:
#  nodeSelector:
#    worker1: production
  https:
    enabled: false
  service:
    type: NodePort
    nodePort: 30080
    nodePorts:
      http: 30080
  chp:
    resources:
      requests:
        cpu: "0.2"
        memory: 512Mi
      limits:
        cpu: "0.5"
        memory: 512Mi
  nginx:
    resources:
      requests:
        cpu: "0.5"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi

auth:
  type: custom
  custom:
    className: "jhub_shibboleth_auth.shibboleth_auth.ShibbolethAuthenticator"
  admin:
    access: false
    users: ['kenan.erdogan@gesis.org', 'arnim.bleier@gesis.org']
  state:
    enabled: true

singleuser:
#  nodeSelector:
#    worker1: production
  schedulerStrategy: spread
  storage:
    capacity: 15Gi
  image:
    name: gesiscss/singleuser-orc
    tag: c81f03fe
  cpu:
    guarantee: 0.2
    limit: 2
  memory:
    guarantee: 2G
    limit: 4G

prePuller:
  continuous:
    enabled: true

cull:
  # kill user pods if idle for 30 mins - default is 1 hour
  timeout: 1800
  every: 660