hub:
  baseUrl: /jupyter/
  image:
    name: gesiscss/k8s-hub-orc-test
    tag: local-6d34234
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
  db:
    type: postgres
  extraConfig: |
    c.Authenticator.admin_users = {'kenan.erdogan@gesis.org', 'arnim.bleier@gesis.org'}
    c.Authenticator.shibboleth_logout_url = 'https://notebooks.gesis.org/Shibboleth.sso/Logout?return=https://notebooks.gesis.org/'
    c.Authenticator.enable_auth_state = True
proxy:
  service:
    type: NodePort
    nodePorts:
      http: 31212
  chp:
    resources:
      requests:
        cpu: 0.2
        memory: 256Mi
auth:
  type: custom
  custom:
    className: "jhub_shibboleth_auth.shibboleth_auth.ShibbolethAuthenticator"
singleuser:
  storage:
    type: none
    capacity: 10Gi
  cpu:
    limit:
    guarantee:
  memory:
    limit: 512M
    guarantee: 512M
  image:
#    name: gesiscss/singleuser-orc
#    tag: f7c8cbb
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.6

prePuller:
  enabled: false

rbac:
  enabled: false