apiVersion: batch/v1
kind: CronJob
metadata:
  name: nfs-backup
spec:
  # At 02:00 in UTC => at 04:00.
  schedule: "0 2 * * *"
  # Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        metadata:
          name: nfs-backup
        spec:
          restartPolicy: OnFailure
          serviceAccount: nfs-backup
          nodeSelector:
            worker1: production  # because of hostPath PVs
          containers:
          - name: nfs-backup
            image: gesiscss/nfs-backup-orc:c81f03fe
            env:
              - name: SSHPASS
                valueFrom:
                  secretKeyRef:
                    name: worker-pass-secret
                    key: password
              - name: BACKUP_FOLDER
                value: "/backup"
              - name: PV_FOLDER
                value: "/export"
            volumeMounts:
              - name: export-volume
                mountPath: /export
              - name: backup-volume
                mountPath: /backup
          volumes:
            - name: export-volume
              hostPath:
                path: /srv/nfs-provisioner
            - name: backup-volume
              hostPath:
                path: /backup/nfs-backup
