apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nfs-backup
spec:
  # At 01:00 in UTC
  schedule: "0 1 * * *"
  # Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        metadata:
          name: nfs-backup
        spec:
          restartPolicy: OnFailure
          serviceAccount: nfs-backup
          nodeSelector:
            # because of hostPath PVs
            production: worker
          containers:
          - name: nfs-backup
            image: gesiscss/nfs-backup-orc:2809db3
            env:
              - name: SSHPASS
                valueFrom:
                  secretKeyRef:
                    name: worker-node-pass
                    key: password
              - name: PV_FOLDER
                value: "/export"
              - name: BACKUP_FOLDER
                value: "/backup"
              - name: MAX_WORKERS
                value: "7"
            volumeMounts:
              - name: export-volume
                mountPath: /export
              - name: backup-volume
                mountPath: /backup
          volumes:
            - name: export-volume
              hostPath:
                path: /srv/nfs-provisioner
            - name: backup-volume
              hostPath:
                path: /srv/nfs-backup
