{{- if .Values.binderhub.networkPolicy.enabled -}}
# copied from https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/templates/netpol.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gesisbinder-users
  labels:
    app: binderhub
    component: user-netpol
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    # apply this to both places user code runs: dind and singleuser-server
    matchExpressions:
      - key: component
        operator: In
        values:
          - singleuser-server
          - dind
    matchLabels:
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  # block ingress unless explicitly allowed by other policies
  # there is an ingress rule defined in z2jh chart (for user pods)
  ingress: []
  egress:
    # allow DNS resolution in the cluster
    # it would be nicer to be able to pin this to only the kube-dns service,
    # but we can only seem to select *pods* not *services* as the destination
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
      to:
        - ipBlock:
            cidr: 10.0.0.0/8
    # allow access to the world,
    # but not the cluster
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
    # By default, Calico uses 192.168.0.0/16 as the Pod network CIDR
    # For flannel to work correctly, you must pass --pod-network-cidr=10.244.0.0/16
    # For Cilium to work correctly, you must pass --pod-network-cidr=10.217.0.0/16 to kubeadm init.
    # 10.244.0.0/16 and 10.217.0.0/16 must be covered by 10.0.0.0/8
    - ports:
        {{ range $port := .Values.binderhub.networkPolicy.egress.tcpPorts }}
        - port: {{ $port }}
          protocol: TCP
        {{ end }}
      to:
      - ipBlock:
          cidr: {{ .Values.binderhub.networkPolicy.egress.cidr }}
          except:
            - 169.254.169.254/32
            - 10.0.0.0/8
#          {{- range $ipOrCidr := .Values.binderhub.networkPolicy.egress.bannedIps }}
#            {{- if (contains $ipOrCidr "/") }}
#            - {{ $ipOrCidr }}
#            {{- else }}
#            - {{ $ipOrCidr}}/32
#            {{- end }}
#          {{- end }}
#    # allow https access to the ingress controller
#    # (needed to fetch public urls hosted on this cluster,
#    # e.g. analytics.mybinder.org)
#    - ports:
#        - port: 443
#          protocol: TCP
#      to:
#        - podSelector:
#            matchLabels:
#              app: nginx-ingress
#              component: controller

{{- end }}
